import { SocialStatus, SummonerData } from '../API/interfaces'

export const summonersData: SummonerData[] = [
	{
		summonerName: 'Dobry mudzin',
		summonerIconId: 5180,
		groupId: 0,
		status: SocialStatus.Online,
		statusMessage: '',
		summonerId: 'mudzin1',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'GG I quit',
		summonerIconId: 29,
		groupId: 0,
		status: SocialStatus.Offline,
		statusMessage: '',
		summonerId: 'mudzin5',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'GigaCweluch',
		summonerIconId: 542,
		groupId: 1,
		status: SocialStatus.Offline,
		statusMessage: 'Jestem cwelem',
		summonerId: 'mudzin25',
		summonerLevel: 69,
		unreadedMessage: true,
	},
	{
		summonerName: 'LittleMati',
		summonerIconId: 534,
		groupId: 1,
		status: SocialStatus.Dnd,
		statusPayload: {
			statusOverride: 'In game (Ranked SR)',
			timeStamp: Date.now(),
		},
		statusMessage: 'Rammus enjoyer 😎',
		summonerId: 'kox',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'ARAMslut1',
		summonerIconId: 51,
		groupId: 3,
		status: SocialStatus.Dnd,
		statusPayload: {
			statusOverride: 'In Game (ARAM)',
			timeStamp: Date.now(),
		},
		statusMessage: 'ARAMy dla podludzi',
		summonerId: 'ARAMslut1',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'ARAMslut2',
		summonerIconId: 60,
		groupId: 3,
		status: SocialStatus.Dnd,
		statusPayload: {
			statusOverride: 'In Queue',
			timeStamp: Date.now(),
		},
		statusMessage: 'ARAMy dla podludzi',
		summonerId: 'ARAMslut2',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'Jeszcze jedna szmata',
		summonerIconId: 55,
		groupId: 3,
		status: SocialStatus.Online,
		statusMessage: 'zeby scroll testowac',
		summonerId: 'ARAMslut2123',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'ARAMslut3',
		summonerIconId: 71,
		groupId: 3,
		status: SocialStatus.Online,
		statusPayload: {
			statusOverride: 'I tak sie nie wyswietli wiec chuj w to :)',
			timeStamp: Date.now(),
		},
		statusMessage: 'ARAMy dla podludzi',
		summonerId: 'ARAMslut3',
		summonerLevel: 69,
		unreadedMessage: true,
	},
	{
		summonerName: '???',
		summonerIconId: 5180,
		groupId: 0,
		status: SocialStatus.Away,
		statusMessage: '',
		summonerId: 'mudzin2',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'Izabela Łęcka',
		summonerIconId: 4796,
		groupId: 2,
		status: SocialStatus.Online,
		statusMessage: 'WOKULSKI WRÓĆ 🥺',
		summonerId: 'LECKAXD',
		summonerLevel: 69,
		unreadedMessage: true,
	},
	{
		summonerName: 'KotoDziwka',
		summonerIconId: 3795,
		groupId: 2,
		status: SocialStatus.Online,
		statusMessage: 'Jestem kurwą',
		summonerId: 'KOTODZIWKA-1',
		summonerLevel: 69,
		unreadedMessage: false,
	},
	{
		summonerName: 'KotoDziwka2',
		summonerIconId: 4655,
		groupId: 2,
		status: SocialStatus.Dnd,
		statusPayload: {
			statusOverride: 'In Champion Select',
			timeStamp: Date.now(),
		},
		statusMessage: 'Jestem kurwą i szmatą',
		summonerId: 'KOTODZIWKA-2',
		summonerLevel: 69,
		unreadedMessage: false,
	},
]
